# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wrm_yB7umSY2IRUyA7d7Bb_FhEpz8MQ1
"""

from sklearn.neighbors import KNeighborsRegressor
import pandas as pd

df=pd.read_csv('london_bike_sharing.csv',  parse_dates=['timestamp'], index_col="timestamp")
df['day_of_week'] = df.index.day_of_week
df_pred=pd.read_csv('temperaturas.csv').values.tolist()

df

x_train=df[['t1','day_of_week']]
y_train=df['cnt']

model=KNeighborsRegressor()
model.fit(x_train,y_train)

for i in df_pred:
  i.append(4)

pred=model.predict(df_pred)

mean = sum(pred)/float(len(pred))
print(mean)
